CREATE DATABASE [LogDB]
GO
USE [LogDB]
GO
CREATE TABLE [dbo].[Logs]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Type] NVARCHAR(50) NULL, 
    [Message] NVARCHAR(150) NULL,
	[Date] DATETIME NULL
)